services:
  # ACA-Py Agent - Configuración simplificada basada en tutorial oficial
  acapy-agent:
    build:
      context: ./aries-cloudagent-python
      dockerfile: docker/Dockerfile.run
      args:
        - PYTHON_VERSION=3.9
    container_name: acapy-agent  
    ports:
      - "8020:8020"  # Admin API
      - "8021:8021"  # Public API
    environment:
      - GENESIS_URL=http://test.bcovrin.vonx.io/genesis
    command:
      - start
      - --auto-provision
      - --seed
      - "Universidad000000000000000000000"
      - --admin
      - "0.0.0.0"
      - "8020"
      - --admin-insecure-mode
      # NOTA: Cambiar a https://utnpf.site cuando configuremos SSL + Nginx proxy
      - --endpoint
      - http://utnpf.site:8021  # HTTP temporal hasta SSL
      - --inbound-transport
      - http
      - "0.0.0.0"
      - "8021"
      - --outbound-transport
      - http
      - --genesis-url
      - http://test.bcovrin.vonx.io/genesis
      - --read-only-ledger
      - --wallet-type
      - askar
      - --wallet-name
      - universidad_wallet
      - --wallet-key
      - universidad_key_segura
      - --log-level
      - INFO
      - --auto-accept-requests
      - --auto-accept-invites
      - --auto-ping-connection
    networks:
      - acapy_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/status/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Controller Python - Integración Moodle + ACA-Py + Fabric
  python-controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: python-controller
    ports:
      - "3000:3000"  # Puerto para Moodle
    environment:
      - ACAPY_ADMIN_URL=http://acapy-agent:8020
      - ACAPY_PUBLIC_URL=http://192.168.100.137:8021
      - FABRIC_NETWORK_PATH=/crypto-config
    volumes:
      - ./crypto-config:/crypto-config:ro
    depends_on:
      acapy-agent:
        condition: service_healthy
    networks:
      - moodle_network
      - fabric_network
      - acapy_network
    restart: unless-stopped

networks:
  moodle_network:
    external:
      name: moodle-project_moodle-network
  fabric_network:
    external:
      name: fabric_test
  acapy_network:
    driver: bridge